/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminYoutubeRouteImport } from './routes/admin.youtube'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminResultsRouteImport } from './routes/admin.results'
import { Route as AdminNoticesRouteImport } from './routes/admin.notices'
import { Route as AdminNotesRouteImport } from './routes/admin.notes'
import { Route as AdminGalleryRouteImport } from './routes/admin.gallery'
import { Route as AdminContactRouteImport } from './routes/admin.contact'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'

const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminYoutubeRoute = AdminYoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultsRoute = AdminResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticesRoute = AdminNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotesRoute = AdminNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactRoute = AdminContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notices': typeof NoticesRoute
  '/results': typeof ResultsRoute
  '/youtube': typeof YoutubeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notices': typeof NoticesRoute
  '/results': typeof ResultsRoute
  '/youtube': typeof YoutubeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/notices': typeof NoticesRoute
  '/results': typeof ResultsRoute
  '/youtube': typeof YoutubeRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/contact': typeof AdminContactRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/notes': typeof AdminNotesRoute
  '/admin/notices': typeof AdminNoticesRoute
  '/admin/results': typeof AdminResultsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/youtube': typeof AdminYoutubeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notes'
    | '/notices'
    | '/results'
    | '/youtube'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/gallery'
    | '/admin/notes'
    | '/admin/notices'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/youtube'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notes'
    | '/notices'
    | '/results'
    | '/youtube'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/gallery'
    | '/admin/notes'
    | '/admin/notices'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/youtube'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/gallery'
    | '/login'
    | '/notes'
    | '/notices'
    | '/results'
    | '/youtube'
    | '/admin/categories'
    | '/admin/contact'
    | '/admin/gallery'
    | '/admin/notes'
    | '/admin/notices'
    | '/admin/results'
    | '/admin/settings'
    | '/admin/youtube'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  NoticesRoute: typeof NoticesRoute
  ResultsRoute: typeof ResultsRoute
  YoutubeRoute: typeof YoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/youtube': {
      id: '/admin/youtube'
      path: '/youtube'
      fullPath: '/admin/youtube'
      preLoaderRoute: typeof AdminYoutubeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/results': {
      id: '/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AdminResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notices': {
      id: '/admin/notices'
      path: '/notices'
      fullPath: '/admin/notices'
      preLoaderRoute: typeof AdminNoticesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notes': {
      id: '/admin/notes'
      path: '/notes'
      fullPath: '/admin/notes'
      preLoaderRoute: typeof AdminNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact': {
      id: '/admin/contact'
      path: '/contact'
      fullPath: '/admin/contact'
      preLoaderRoute: typeof AdminContactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminContactRoute: typeof AdminContactRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminNotesRoute: typeof AdminNotesRoute
  AdminNoticesRoute: typeof AdminNoticesRoute
  AdminResultsRoute: typeof AdminResultsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminYoutubeRoute: typeof AdminYoutubeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminContactRoute: AdminContactRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminNotesRoute: AdminNotesRoute,
  AdminNoticesRoute: AdminNoticesRoute,
  AdminResultsRoute: AdminResultsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminYoutubeRoute: AdminYoutubeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  NoticesRoute: NoticesRoute,
  ResultsRoute: ResultsRoute,
  YoutubeRoute: YoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
